# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: mf_modulsuche
version: '1.2'
author: 'Daniel Springer | Medienfeuer'
compile: 0
supportpage: https://github.com/danspringer/mf_modulsuche

pages:
  modules/mf_modulsuche:
    title: translate:title
    perm: mf_modulsuche[]
    pjax: true
    #icon: rex-icon fa fa-search
    subpages:
      config: { title: 'translate:mf_modulsuche_configuration' }
      start: { title: 'translate:mf_modulsuche_start', subPath: README.md  } # config-Seite mit separaten Rechten

load: late

requires:
    packages:
      structure: '>=2.0'
    
    redaxo: '>=5.0'